# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/asr_teach',
                'doc_host': 'https://enzokro.github.io',
                'git_url': 'https://github.com/enzokro/asr_teach',
                'lib_path': 'asr_teach'},
  'syms': {'asr_teach.core': {'asr_teach.core.foo': ('core.html#foo', 'asr_teach/core.py')}}}
