# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_utils.ipynb.

# %% auto 0
__all__ = ['SAMPLE_RATE', 'BUFFER_SECONDS', 'DTYPE', 'DEVICE', 'BLOCK_DURATION', 'PROTOCOL', 'ADDR', 'PORT', 'ZMQ_ARGS']

# %% ../nbs/10_utils.ipynb 1
import numpy as np

# %% ../nbs/10_utils.ipynb 2
# audio constants
SAMPLE_RATE = 48_000
BUFFER_SECONDS = 2
DTYPE = np.int16
DEVICE = 0
BLOCK_DURATION = 50


# default streaming args for ZMQ sockets
PROTOCOL = 'tcp'
ADDR = '127.0.0.1'
PORT = 9090


# for sending numpy arrays
ZMQ_ARGS = {
    'flags': 0,
    'copy': True,
    'track': False,
}
